export const SERVER_CATALOG = {
  arma3: [
    {
      id: 'arma3-cth-primary',
      title: 'T-Central Arma3 CTH',
      ip: 'tcentral.game.nfoservers.com:2302',
      game: 'Arma 3',
      mode: 'CTH',
      map: 'Altis',
      tier: 'Primary',
      steamAppId: '107410',
      statusKey: 'arma3',
      tags: ['arma3', 'cth', 'altis', 'primary'],
    },
    {
      id: 'arma3-cth-training',
      title: 'T-Central Arma3 Training',
      ip: 'tcentral.game.nfoservers.com:2402',
      game: 'Arma 3',
      mode: 'Training',
      map: 'Altis',
      tier: 'Training',
      steamAppId: '107410',
      tags: ['arma3', 'training', 'altis'],
    },
    {
      id: 'arma3-cth-event',
      title: 'T-Central Arma3 Event',
      ip: 'tcentral.game.nfoservers.com:2502',
      game: 'Arma 3',
      mode: 'Event',
      map: 'Rotating',
      tier: 'Event',
      steamAppId: '107410',
      tags: ['arma3', 'event', 'rotating'],
    },
  ],
};
