export const SERVER_DEFINITIONS = [
  {
    id: 'arma3-cth-primary',
    slug: 'arma3-cth',
    statusKey: 'arma3',
    title: 'T-Central Arma3 CTH',
    shortTitle: 'Arma3 CTH',
    href: '/servers/arma3-cth',
    ip: 'tcentral.game.nfoservers.com:2302',
    game: 'Arma 3',
    mode: 'CTH',
    map: 'Altis',
    tier: 'Primary',
    maxPlayers: 60,
    steamAppId: '107410',
    source: 'No status source configured',
    reportLabel: 'Arma3 CTH',
    tags: ['arma3', 'cth', 'altis', 'primary'],
  },
  {
    id: 'rust-biweekly-primary',
    slug: 'rust-biweekly',
    statusKey: 'rust_biweekly',
    title: 'T-Central Rust Bi-Weekly',
    shortTitle: 'Rust Bi-Weekly',
    href: '/servers/rust-biweekly',
    ip: 'tcentralrust.game.nfoservers.com:28015',
    game: 'Rust',
    mode: 'Vanilla',
    map: 'Procedural Map',
    tier: 'Primary',
    maxPlayers: 250,
    wipeCadence: 'Bi-Weekly Wipe',
    source: 'No status source configured',
    reportLabel: 'Rust Bi-Weekly',
    tags: ['rust', 'vanilla', 'biweekly', 'primary'],
  },
  {
    id: 'rust-weekly-primary',
    slug: 'rust-weekly',
    statusKey: 'rust_weekly',
    title: 'T-Central Rust Weekly',
    shortTitle: 'Rust Weekly',
    href: '/servers/rust-weekly',
    ip: 'tcentralrust2.game.nfoservers.com:28015',
    game: 'Rust',
    mode: 'Vanilla',
    map: 'Procedural Map',
    tier: 'Primary',
    maxPlayers: 250,
    wipeCadence: 'Weekly Wipe',
    source: 'No status source configured',
    reportLabel: 'Rust Weekly',
    tags: ['rust', 'vanilla', 'weekly', 'primary'],
  },
  {
    id: 'rust-monthly-primary',
    slug: 'rust-monthly',
    statusKey: 'rust_monthly',
    title: 'T-Central Rust Monthly',
    shortTitle: 'Rust Monthly',
    href: '/servers/rust-monthly',
    ip: 'tcentralrust3.game.nfoservers.com:28015',
    game: 'Rust',
    mode: 'Vanilla',
    map: 'Procedural Map',
    tier: 'Primary',
    maxPlayers: 250,
    wipeCadence: 'Monthly Wipe',
    source: 'No status source configured',
    reportLabel: 'Rust Monthly',
    tags: ['rust', 'vanilla', 'monthly', 'primary'],
  },
  {
    id: 'rust-vanilla-overview',
    slug: 'rust-vanilla',
    statusKey: 'rust_biweekly',
    title: 'T-Central Rust Vanilla',
    shortTitle: 'Rust Vanilla',
    href: '/servers/rust-vanilla',
    ip: 'tcentralrust.game.nfoservers.com:28015',
    game: 'Rust',
    mode: 'Vanilla',
    map: 'Procedural Map',
    tier: 'Overview',
    maxPlayers: 250,
    wipeCadence: 'Bi-Weekly Wipe',
    source: 'No status source configured',
    reportLabel: 'Rust Vanilla',
    tags: ['rust', 'vanilla', 'overview'],
  },
];

export const PRIMARY_SERVER_ROUTES = SERVER_DEFINITIONS.filter((server) => server.tier !== 'Overview');

export const STATUS_DEFAULTS = Object.fromEntries(
  PRIMARY_SERVER_ROUTES.map((server) => [
    server.statusKey,
    {
      key: server.statusKey,
      name: server.shortTitle,
      online: null,
      players: 0,
      maxPlayers: server.maxPlayers ?? null,
      map: server.map ?? null,
      source: server.source,
    },
  ])
);

export const REPORT_SERVER_OPTIONS = ['T-Central Hub', ...PRIMARY_SERVER_ROUTES.map((server) => server.reportLabel)];

export const SITE_ROUTES = [
  '',
  '/system',
  '/information',
  '/server-info',
  '/status',
  '/donate',
  '/privacy-policy',
  '/terms-and-conditions',
  '/report-player',
  ...SERVER_DEFINITIONS.map((server) => server.href),
];

export function getServerBySlug(slug) {
  return SERVER_DEFINITIONS.find((server) => server.slug === slug) ?? null;
}
